# Generated by Django 4.2.11 on 2026-04-30 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='weekly', max_length=20)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Repeat every N days/weeks/months/years')),
                ('by_day', models.CharField(blank=True, help_text='Comma-separated weekdays (MO,TU,WE,TH,FR,SA,SU)', max_length=50)),
                ('by_month_day', models.PositiveIntegerField(blank=True, help_text='Day of the month (1-31)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Stop repeating after this date', null=True)),
                ('count', models.PositiveIntegerField(blank=True, help_text='Number of occurrences', null=True)),
            ],
            options={
                'verbose_name': 'Recurrence Rule',
                'verbose_name_plural': 'Recurrence Rules',
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='occurrence_date',
            field=models.DateField(blank=True, null=True, verbose_name='Occurrence Date'),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('user', 'event', 'occurrence_date')},
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.recurrencerule', verbose_name='Recurrence Rule'),
        ),
    ]
