# Generated by Django 4.2.11 on 2026-04-20 08:49

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('title', models.CharField(max_length=100, verbose_name='Title/Role')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('image', models.ImageField(upload_to='board/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Board Member',
                'verbose_name_plural': 'Board Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('org_number', models.CharField(max_length=50, verbose_name='Organization Number')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('address', models.TextField(verbose_name='Address')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Founded Year')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('mission', models.TextField(blank=True, verbose_name='Mission')),
                ('vision', models.TextField(blank=True, verbose_name='Vision')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Short Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'Site Settings Translation',
                'db_table': 'core_sitesettings_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
