# Generated by Django 4.2.11 on 2026-04-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Hero Background'),
        ),
    ]
