# Generated by Django 4.2.11 on 2026-04-23 07:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_hero_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_background',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_background'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
